### ISSUE TITLE
model.py中的对中文做embedding操作

### ISSUE THREAD

**Issue by mirror111** [hzy46/Char-RNN-TensorFlow#1]
embedding = tf.get_variable('embedding', [self.num_classes, self.embedding_size])
self.lstm_inputs = tf.nn.embedding_lookup(embedding, self.inputs)
这样就直接变成了中文的embedding表示吗？不是很明白这两句的意思

**Comment by hzy46** [comment]
简单来讲，就是把一个3000维（假设有3000个汉字）的向量投影到128维的空间里。这样数据就不像原来那么稀疏，利于模型学习。

至于函数的功能你可以直接参考文档。

**Comment by mirror111** [comment]
tf.get_variable() 我看是随机生成了[self.num_classes, self.embedding_size]的一组tensor，这个可以来表示每个汉字的embedding吗？不是需要一个训练的过程吗？类似word2vec那样

**Comment by mirror111** [comment]
我之前是直接用word2vec生成每个词的embedding然后再用神经网络做处理，所以不太清楚这种embedding的逻辑。。。

**Comment by hzy46** [comment]
初始是随机的。相当于我们同时训练了embedding和RNN，懂了么

**Comment by mirror111** [comment]
ok，非常感谢
